apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "event-contract-guard.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "event-contract-guard.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "event-contract-guard.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "event-contract-guard.name" . }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
